spring:
  application:
    name: gateway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    ldap:
      enabled: false

zuul:
  sensitiveHeaders:

  routes: &routes
    web:
      path: '/web/**'
      serviceId: 'web'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

info:
  routes: *routes

jwt:
  expirationInMs: '604800000'
  secret: s3cr3t
